- name: Run "apt-get update"
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Install HashiCorp dependencies
  apt:
    name:
      - curl
      - unzip
      - jq
    state: present
    update_cache: true
  register: pkg_dependencies
  retries: 12
  delay: 20
  until: pkg_dependencies is success

- import_tasks: consul.yml

- import_tasks: nomad.yml

- import_tasks: vault.yml

- import_tasks: post-install.yml
