- name: Download Nomad
  when: not nomad_premium|bool
  get_url:
    url:
      "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{
      nomad_version }}_linux_amd64.zip"
    dest: "/tmp/nomad_{{ nomad_version }}_linux_amd64.zip"
    checksum:
      "sha256:https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{
      nomad_version }}_SHA256SUMS"

- name: Download Nomad Premium from GCP Bucket
  when: nomad_premium|bool
  shell:
    "/snap/bin/gsutil cp gs://sandbox-bin/nomad/{{ nomad_version
    }}/nomad-enterprise_{{ nomad_version }}+ent_linux_amd64.zip
    /tmp/nomad-enterprise_{{ nomad_version }}+ent_linux_amd64.zip"

- name: Unarchive Nomad
  when: not nomad_premium|bool
  unarchive:
    src: "/tmp/nomad_{{ nomad_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    owner: root
    group: root
    remote_src: yes

- name: Unarchive Nomad Premium
  when: nomad_premium|bool
  unarchive:
    src: "/tmp/nomad-enterprise_{{ nomad_version }}+ent_linux_amd64.zip"
    dest: /usr/local/bin
    owner: root
    group: root
    remote_src: yes

- name: Setup Nomad autocompletion
  copy:
    content: complete -C "/usr/local/bin/nomad" "nomad"
    dest: /etc/profile.d/99-nomad-completion.sh
    mode: "0644"

- name: Create Nomad user
  user:
    name: nomad
    system: yes
    shell: /bin/false
    home: "/etc/nomad.d"
    create_home: no
    append: yes

- name: Create Nomad configuration
  file:
    path: "/etc/nomad.d"
    state: directory
    owner: nomad
    group: nomad
    mode: "0750"

- name: Create Nomad data directory
  file:
    path: /opt/nomad
    state: directory
    owner: nomad
    group: nomad
    mode: "0700"

- name: Install Nomad systemd unit
  template:
    src: etc/systemd/system/nomad.service.j2
    dest: /etc/systemd/system/nomad.service
